#!/usr/bin/env python

import numpy as np
from evo.tools.file_interface import read_tum_trajectory_file, write_tum_trajectory_file
from evo.core import trajectory


class TrajectorySorter:
    """
    Reverse the timestamp of the estimated trajectory generated by CCMSLAM
    """
    def __init__(self, base_path, est_file, est_file_sorted):
        self.base_path = base_path
        self.est_file = self.base_path + est_file
        self.est_file_sorted = self.base_path + est_file_sorted

    def sort_trajectory(self):
        est_traj = read_tum_trajectory_file(self.est_file)

        sorted_indices = np.argsort(est_traj.timestamps)
        sorted_timestamps = est_traj.timestamps[sorted_indices]
        sorted_poses = [est_traj.poses_se3[i] for i in sorted_indices]
        sorted_traj = trajectory.PoseTrajectory3D(poses_se3=sorted_poses, timestamps=sorted_timestamps)

        write_tum_trajectory_file(self.est_file_sorted, sorted_traj)
        print("Trajectory sorted successfully: {0}".format(self.est_file_sorted))


if __name__ == "__main__":
    base_path = "/home/zuyuan/Documents/dataset/kitti/Traj_Vis/Self_trained_ORBvoc_seq00/seq02_2-3.5_12-13/"
    est_file = "KF_GBA_1.csv"
    est_file_sorted = "KF_GBA_1_sorted.csv"
    sorter = TrajectorySorter(base_path, est_file, est_file_sorted)
    sorter.sort_trajectory()
